In [1]:
import numpy as np

## numpy array

In [2]:
listem = [10,25,35]

In [4]:
np.array(listem) # numpy arrayine donusturduk

array([10, 25, 35])

In [5]:
matrixListem = [[1,2,3],[10,20,30],[100,200,300]]

In [6]:
np.array(matrixListem)

array([[  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300]])

## arange

In [9]:
list(range(0,10)) # listelerde kullandigimiz range fonksiyonu

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

## zeros

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

## ones

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## linspace

In [19]:
np.linspace(0,20,6) # aralarinda esit mesafe olan 6 tane rakam olusturdu

array([ 0.,  4.,  8., 12., 16., 20.])

## eye

In [21]:
np.eye(10) # 10a 10luk birim matris yapar

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## random

In [28]:
np.random.randn(5) #-1 0 ve 1li rastgele 5 sayi ver

array([-0.40186361,  0.37090552,  0.47305659,  1.10641969, -0.17498704])

In [24]:
np.random.randn(3,4)

array([[ 0.8765687 ,  0.20678593, -0.47350336,  0.05760725],
       [-0.33456299,  0.7765141 , -0.4890345 , -0.51998832],
       [-0.72873513, -0.61260779,  0.95636608,  0.23979251]])

In [25]:
np.random.randint(1,100) # 1 ile 100 arasi bir sayi

46

In [27]:
np.random.randint(1,20,5) # 1 ile 20 arasi 5 sayi

array([10,  9, 14, 11,  1])

In [33]:
benimNumpyDizim = np.arange(30)

In [34]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [31]:
randomDizim = np.random.randint(1,100,20)

In [32]:
randomDizim

array([86, 35, 76, 54, 29, 27, 75, 82, 88, 66, 90, 36, 94, 83, 68, 13,  2,
        5, 65, 49])

## numpy dizi methodlari

In [36]:
benimNumpyDizim.reshape(5,6) # 30 karakter oldugu icin 5satir 6sutunlu olacak

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [39]:
benimNumpyDizim.max() # en buyuk sayiyi verir

29

In [41]:
benimNumpyDizim.min() # en kucuk sayiyi verir

0

In [49]:
randomDizim.argmax() #en buyuk sayinin kacinci indexte onu verir

12

In [50]:
randomDizim.argmin() #en kucuk sayinin kacinci indexte onu verir

16

In [53]:
benimNumpyDizim.shape # dizimiz tek boyutlu oldugu icin 30 karakteri verir

(30,)

In [54]:
benimShapeDizim = benimNumpyDizim.reshape(6,5)

In [56]:
benimShapeDizim.shape # 6ya 5lik bir dizi diye bastirir

(6, 5)

## numpy operasyonlari

In [58]:
benimDizi = np.arange(0,15)

In [59]:
benimDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [60]:
benimDizi[3:10]

array([3, 4, 5, 6, 7, 8, 9])

In [61]:
benimDizi[10:15] = -1

In [62]:
benimDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, -1, -1, -1, -1, -1])

In [63]:
ornekDizi = np.arange(0,25)

In [72]:
ornekDiziKopya = ornekDizi.copy() # ana diziyi etkilememesi icin copy diyoruz,
#yoksa ana diziden kopyaladigimiz bir parcada yaptigimiz degisiklikler ana diziyide etkiler

In [74]:
ornekDiziKopyaSlicing = ornekDiziKopya[1:10]

In [75]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [76]:
ornekDiziKopyaSlicing[:] = 999

In [77]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [79]:
ornekDiziKopya # kopya diziyi etkiledi

array([  0, 999, 999, 999, 999, 999, 999, 999, 999, 999,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

## matrix

In [80]:
benimListem = [[10,20,30],[40,50,60],[70,80,90]]

In [81]:
benimMatrix = np.array(benimListem)

In [82]:
benimMatrix

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [84]:
benimMatrix[0:2]

array([[10, 20, 30],
       [40, 50, 60]])

In [85]:
benimMatrix[0][1]

20

In [87]:
benimMatrix[0,1] # ikisi ayni sey

20

In [89]:
benimMatrix[0:,2] # 0. satirdan itibaren her satirin 2. elemanini getir

array([30, 60, 90])

In [90]:
benimMatrix[0:,1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [96]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [97]:
yeniMatrix = np.array(yeniListe)

In [98]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [100]:
yeniMatrix[[0,2,4]] # 0,2,4. satirlari getir

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

## operasyonlar

In [111]:
yeniBirDizi = np.random.randint(0,100,20)

In [112]:
yeniBirDizi

array([46, 69, 52,  1, 20, 82,  7, 40, 84, 23,  6, 94, 28, 63, 61, 82, 14,
       56,  2, 16])

In [123]:
yeniBirDizi > 30 # 30dan buyuk elemanlari true veya false olarak dondurur

array([ True,  True,  True, False, False,  True, False,  True,  True,
       False, False,  True, False,  True,  True,  True, False,  True,
       False, False])

In [124]:
boolDizisi = yeniBirDizi > 30

In [125]:
boolDizisi

array([ True,  True,  True, False, False,  True, False,  True,  True,
       False, False,  True, False,  True,  True,  True, False,  True,
       False, False])

In [126]:
yeniBirDizi[boolDizisi] # sadece 30dan buyuk olanlari aldik

array([46, 69, 52, 82, 40, 84, 94, 63, 61, 82, 56])

In [128]:
yeniBirDizi[yeniBirDizi > 50] # bu sekildede yapabiliriz

array([69, 52, 82, 84, 94, 63, 61, 82, 56])

In [129]:
yeniBirDizi

array([46, 69, 52,  1, 20, 82,  7, 40, 84, 23,  6, 94, 28, 63, 61, 82, 14,
       56,  2, 16])

In [130]:
toplamaDizi = np.arange(0,10)

In [132]:
toplamaDizi + toplamaDizi # dizileri +-*/ bolme islemleri yapabiliriz

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [134]:
np.sqrt(toplamaDizi) # karekokunu alma

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [135]:
np.max(toplamaDizi)

9